from typing import NamedTuple, Any


class ResolverInputSet(NamedTuple):
    parent: Any = ...
    driver: Any = ...
    locator: Any = ...
    full_locator: str = ...
    strategy: str = ...
    logger: Any = ...
